// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa8Ux75jWgf9eOWG86io4F9a6DEvINAi4',
    appId: '1:689930648007:web:a6ef59c009ad5454c441e2',
    messagingSenderId: '689930648007',
    projectId: 'budget-app-1111',
    authDomain: 'budget-app-1111.firebaseapp.com',
    storageBucket: 'budget-app-1111.firebasestorage.app',
    measurementId: 'G-7GPXG2P6LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSNXToH4zrdquuPKNy1wORmIOYwgpikU',
    appId: '1:689930648007:android:56d1fccdbb069944c441e2',
    messagingSenderId: '689930648007',
    projectId: 'budget-app-1111',
    storageBucket: 'budget-app-1111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnCdeCmRGoalZLFbW77fFv0DyiMhfsxE',
    appId: '1:689930648007:ios:c644636b9a49755ec441e2',
    messagingSenderId: '689930648007',
    projectId: 'budget-app-1111',
    storageBucket: 'budget-app-1111.firebasestorage.app',
    androidClientId: '689930648007-6mjiufqq0k4g5auabml4u22i2560ovrn.apps.googleusercontent.com',
    iosClientId: '689930648007-b60pa0f6lbubhbjid9bagg52gucl09p1.apps.googleusercontent.com',
    iosBundleId: 'com.set.budget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnCdeCmRGoalZLFbW77fFv0DyiMhfsxE',
    appId: '1:689930648007:ios:c644636b9a49755ec441e2',
    messagingSenderId: '689930648007',
    projectId: 'budget-app-1111',
    storageBucket: 'budget-app-1111.firebasestorage.app',
    androidClientId: '689930648007-6mjiufqq0k4g5auabml4u22i2560ovrn.apps.googleusercontent.com',
    iosClientId: '689930648007-b60pa0f6lbubhbjid9bagg52gucl09p1.apps.googleusercontent.com',
    iosBundleId: 'com.set.budget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa8Ux75jWgf9eOWG86io4F9a6DEvINAi4',
    appId: '1:689930648007:web:c218b3edcb93df5ac441e2',
    messagingSenderId: '689930648007',
    projectId: 'budget-app-1111',
    authDomain: 'budget-app-1111.firebaseapp.com',
    storageBucket: 'budget-app-1111.firebasestorage.app',
    measurementId: 'G-GFCCB38KT8',
  );
}
